# coding: utf-8

"""
    Speech Services API v3.1

    Speech Services API v3.1.  # noqa: E501

    OpenAPI spec version: v3.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import azure_speech_api
from azure_speech_api.models.transcriptions_locales_get200_application_json_response import TranscriptionsLocalesGet200ApplicationJsonResponse  # noqa: E501
from azure_speech_api.rest import ApiException


class TestTranscriptionsLocalesGet200ApplicationJsonResponse(unittest.TestCase):
    """TranscriptionsLocalesGet200ApplicationJsonResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTranscriptionsLocalesGet200ApplicationJsonResponse(self):
        """Test TranscriptionsLocalesGet200ApplicationJsonResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = azure_speech_api.models.transcriptions_locales_get200_application_json_response.TranscriptionsLocalesGet200ApplicationJsonResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
